[theme]

# Primary accent for interactive elements
primaryColor = '#4C1434'

# Background color for the main content area
# backgroundColor = '#4C1434'
# backgroundColor = '#D9D9D9'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#D9D9D9'

# Color used for almost all text
textColor = '#060606'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
